# Seed data for Kerjo. Exact data from the product brief.

def av(n):
    return f"https://i.pravatar.cc/600?img={n}"


WORKERS = [
    {"id": "wk_1", "name": "Siti Aminah", "category": "Bersih-bersih", "role": "Bersih-bersih Rumah",
     "experience_label": "3 tahun", "experience_years": 3, "distance_km": 2.1, "pay_amount": 35000,
     "pay_unit": "/jam", "rating": 4.9, "jobs_completed": 31, "verified": True, "is_new": False,
     "avatar": av(5), "bio": "Rapi, teliti, dan selalu tepat waktu. Berpengalaman bersih-bersih rumah dan apartemen."},
    {"id": "wk_2", "name": "Bambang Hartono", "category": "Tukang", "role": "Tukang / Handyman",
     "experience_label": "7 tahun", "experience_years": 7, "distance_km": 4.5, "pay_amount": 150000,
     "pay_unit": "/hari", "rating": 4.7, "jobs_completed": 58, "verified": True, "is_new": False,
     "avatar": av(12), "bio": "Bisa perbaikan listrik, keran, cat, dan renovasi ringan. Kerja bersih dan rapi."},
    {"id": "wk_3", "name": "Dedi Kurniawan", "category": "Supir", "role": "Supir Pribadi",
     "experience_label": "5 tahun", "experience_years": 5, "distance_km": 1.8, "pay_amount": 3500000,
     "pay_unit": "/bulan", "rating": 4.8, "jobs_completed": 19, "verified": True, "is_new": False,
     "avatar": av(11), "bio": "SIM A & B, hafal jalan kota. Sopan, sabar, dan siap antar jemput keluarga."},
    {"id": "wk_4", "name": "Rina Wulandari", "category": "Pengasuh Anak", "role": "Pengasuh Anak / Babysitter",
     "experience_label": "4 tahun", "experience_years": 4, "distance_km": 3.0, "pay_amount": 2800000,
     "pay_unit": "/bulan", "rating": 5.0, "jobs_completed": 14, "verified": True, "is_new": False,
     "avatar": av(9), "bio": "Sayang anak, telaten, dan paham gizi balita. Pengalaman jaga bayi hingga usia sekolah."},
    {"id": "wk_5", "name": "Agus Setiawan", "category": "Kuli Bangunan", "role": "Kuli Bangunan",
     "experience_label": "2 tahun", "experience_years": 2, "distance_km": 5.2, "pay_amount": 130000,
     "pay_unit": "/hari", "rating": 4.5, "jobs_completed": 22, "verified": True, "is_new": False,
     "avatar": av(13), "bio": "Kuat, rajin, dan tahan kerja lapangan. Siap bantu angkut, cor, dan pasang bata."},
    {"id": "wk_6", "name": "Wati Lestari", "category": "Masak", "role": "Masak / Catering Rumahan",
     "experience_label": "6 tahun", "experience_years": 6, "distance_km": 2.7, "pay_amount": 250000,
     "pay_unit": "/acara", "rating": 4.9, "jobs_completed": 40, "verified": True, "is_new": False,
     "avatar": av(10), "bio": "Masakan rumahan enak dan higienis. Bisa masak untuk acara keluarga dan kantor."},
    {"id": "wk_7", "name": "Joko Prasetyo", "category": "Kurir", "role": "Kurir / Delivery",
     "experience_label": "1 tahun", "experience_years": 1, "distance_km": 1.2, "pay_amount": 25000,
     "pay_unit": "/pengiriman", "rating": 4.6, "jobs_completed": 65, "verified": True, "is_new": False,
     "avatar": av(15), "bio": "Motor sendiri, cepat dan amanah. Siap antar barang ke mana saja dalam kota."},
    {"id": "wk_8", "name": "Yuni Astuti", "category": "Kebun", "role": "Tukang Kebun",
     "experience_label": "Baru", "experience_years": 0, "distance_km": 3.8, "pay_amount": 100000,
     "pay_unit": "/hari", "rating": 0, "jobs_completed": 0, "verified": False, "is_new": True,
     "avatar": av(16), "bio": "Baru mulai di Kerjo, semangat dan mau belajar. Suka merawat tanaman dan taman."},
    {"id": "wk_9", "name": "Slamet Riyadi", "category": "Bersih-bersih", "role": "ART Harian",
     "experience_label": "8 tahun", "experience_years": 8, "distance_km": 2.4, "pay_amount": 120000,
     "pay_unit": "/hari", "rating": 4.8, "jobs_completed": 72, "verified": True, "is_new": False,
     "avatar": av(14), "bio": "Serba bisa urus rumah: bersih-bersih, cuci, setrika. Jujur dan bisa dipercaya."},
    {"id": "wk_10", "name": "Nur Hidayah", "category": "Bersih-bersih", "role": "Cleaning Service Kos/Kantor",
     "experience_label": "2 tahun", "experience_years": 2, "distance_km": 4.0, "pay_amount": 40000,
     "pay_unit": "/jam", "rating": 4.7, "jobs_completed": 28, "verified": True, "is_new": False,
     "avatar": av(20), "bio": "Spesialis bersih kos dan kantor. Cepat, wangi, dan detail sampai sudut ruangan."},
    {"id": "wk_11", "name": "Putri Ramadhani", "category": "Desain", "role": "Desainer Grafis",
     "experience_label": "2 tahun", "experience_years": 2, "distance_km": 3.5, "pay_amount": 150000,
     "pay_unit": "/desain", "rating": 4.8, "jobs_completed": 17, "verified": True, "is_new": False,
     "avatar": av(31), "bio": "Desain logo, feed IG, dan poster. Kreatif, revisi cepat, hasil kekinian."},
    {"id": "wk_12", "name": "Fajar Nugroho", "category": "Admin/Sosmed", "role": "Admin Media Sosial",
     "experience_label": "Baru", "experience_years": 0, "distance_km": 2.9, "pay_amount": 1800000,
     "pay_unit": "/bulan", "rating": 0, "jobs_completed": 0, "verified": False, "is_new": True,
     "avatar": av(33), "bio": "Baru gabung Kerjo. Aktif main sosmed, siap bantu kelola konten UMKM."},
    {"id": "wk_13", "name": "Dewi Anggraini", "category": "Menulis", "role": "Content Writer",
     "experience_label": "3 tahun", "experience_years": 3, "distance_km": 6.1, "pay_amount": 75000,
     "pay_unit": "/artikel", "rating": 4.9, "jobs_completed": 33, "verified": True, "is_new": False,
     "avatar": av(32), "bio": "Nulis artikel SEO, blog, dan caption. Riset rapi dan tepat deadline."},
    {"id": "wk_14", "name": "Rizky Firmansyah", "category": "Admin/Sosmed", "role": "Entry Data / Admin",
     "experience_label": "1 tahun", "experience_years": 1, "distance_km": 1.5, "pay_amount": 2200000,
     "pay_unit": "/bulan", "rating": 4.6, "jobs_completed": 11, "verified": True, "is_new": False,
     "avatar": av(51), "bio": "Cepat dan teliti input data, jago Excel. Rapi dalam administrasi kantor."},
    {"id": "wk_15", "name": "Ayu Kusuma", "category": "Tutor", "role": "Tutor Matematika SD-SMP",
     "experience_label": "4 tahun", "experience_years": 4, "distance_km": 2.2, "pay_amount": 80000,
     "pay_unit": "/jam", "rating": 5.0, "jobs_completed": 25, "verified": True, "is_new": False,
     "avatar": av(45), "bio": "Sabar dan telaten mengajar. Bikin matematika jadi mudah dan menyenangkan."},
    {"id": "wk_16", "name": "Bayu Saputra", "category": "Fotografi/Video", "role": "Video Editor Freelance",
     "experience_label": "2 tahun", "experience_years": 2, "distance_km": 5.5, "pay_amount": 200000,
     "pay_unit": "/video", "rating": 4.7, "jobs_completed": 20, "verified": True, "is_new": False,
     "avatar": av(52), "bio": "Edit video reels, YouTube, dan iklan. Cepat, rapi, dan sesuai brief."},
    {"id": "wk_17", "name": "Indah Permatasari", "category": "CS", "role": "Customer Service",
     "experience_label": "3 tahun", "experience_years": 3, "distance_km": 3.3, "pay_amount": 2500000,
     "pay_unit": "/bulan", "rating": 4.8, "jobs_completed": 29, "verified": True, "is_new": False,
     "avatar": av(44), "bio": "Ramah dan sabar melayani pelanggan. Fast response chat dan telepon."},
    {"id": "wk_18", "name": "Hendra Gunawan", "category": "Fotografi/Video", "role": "Fotografer Event",
     "experience_label": "5 tahun", "experience_years": 5, "distance_km": 4.8, "pay_amount": 500000,
     "pay_unit": "/event", "rating": 4.9, "jobs_completed": 36, "verified": True, "is_new": False,
     "avatar": av(53), "bio": "Foto wedding, ulang tahun, dan acara kantor. Hasil tajam dan hidup."},
    {"id": "wk_19", "name": "Sri Wahyuni", "category": "Admin/Sosmed", "role": "Admin Toko Online",
     "experience_label": "Baru", "experience_years": 0, "distance_km": 2.6, "pay_amount": 1900000,
     "pay_unit": "/bulan", "rating": 0, "jobs_completed": 0, "verified": False, "is_new": True,
     "avatar": av(49), "bio": "Baru mulai di Kerjo. Rapi balas chat pembeli dan urus pesanan toko online."},
    {"id": "wk_20", "name": "Taufik Hidayat", "category": "Web Dev", "role": "Web Developer Pemula",
     "experience_label": "1 tahun", "experience_years": 1, "distance_km": 3.9, "pay_amount": 1500000,
     "pay_unit": "/proyek", "rating": 4.5, "jobs_completed": 8, "verified": True, "is_new": False,
     "avatar": av(60), "bio": "Bikin landing page dan website UMKM. Belajar cepat dan komunikatif."},
]


JOBS = [
    {"id": "jb_1", "business": "Keluarga Santoso", "title": "Butuh ART Harian", "category": "Bersih-bersih",
     "pay_amount": 120000, "pay_unit": "/hari", "distance_km": 2.0, "job_type": "Harian",
     "min_experience_label": "Min. 1 tahun", "description": "Cari ART harian untuk bersih-bersih rumah, cuci, dan setrika. Ramah dan jujur."},
    {"id": "jb_2", "business": "Toko Bangunan Jaya", "title": "Kuli Angkut Barang", "category": "Kuli Bangunan",
     "pay_amount": 140000, "pay_unit": "/hari", "distance_km": 3.5, "job_type": "Harian",
     "min_experience_label": "Min. Tidak wajib", "description": "Butuh tenaga angkut material bangunan. Kuat dan siap kerja lapangan."},
    {"id": "jb_3", "business": "Rumah Tangga Wijaya", "title": "Supir Antar Jemput Anak", "category": "Supir",
     "pay_amount": 3200000, "pay_unit": "/bulan", "distance_km": 1.9, "job_type": "Part-time",
     "min_experience_label": "Min. 3 tahun", "description": "Antar jemput anak sekolah pagi & siang. Sopan, sabar, dan tepat waktu."},
    {"id": "jb_4", "business": "Warung Bu Yanti", "title": "Bantu Masak & Bersih-bersih", "category": "Masak",
     "pay_amount": 100000, "pay_unit": "/hari", "distance_km": 2.5, "job_type": "Harian",
     "min_experience_label": "Min. Tidak wajib", "description": "Bantu masak menu warung dan beres-beres dapur. Rajin dan bersih."},
    {"id": "jb_5", "business": "Kos Melati", "title": "Cleaning Service Mingguan", "category": "Bersih-bersih",
     "pay_amount": 350000, "pay_unit": "/minggu", "distance_km": 4.1, "job_type": "Part-time",
     "min_experience_label": "Min. 1 tahun", "description": "Bersihkan area kos setiap minggu: koridor, kamar mandi umum, dan halaman."},
    {"id": "jb_6", "business": "Keluarga Pratama", "title": "Pengasuh Anak Full-time", "category": "Pengasuh Anak",
     "pay_amount": 2700000, "pay_unit": "/bulan", "distance_km": 3.2, "job_type": "Full-time",
     "min_experience_label": "Min. 2 tahun", "description": "Menjaga 2 anak (3 & 6 tahun). Telaten, sabar, dan sayang anak."},
    {"id": "jb_7", "business": "Ekspedisi Cepat", "title": "Kurir Motor Harian", "category": "Kurir",
     "pay_amount": 150000, "pay_unit": "/hari", "distance_km": 1.4, "job_type": "Harian",
     "min_experience_label": "Min. Tidak wajib", "description": "Antar paket area kota. Punya motor sendiri, SIM C aktif."},
    {"id": "jb_8", "business": "Perumahan Griya Asri", "title": "Tukang Kebun Bulanan", "category": "Kebun",
     "pay_amount": 800000, "pay_unit": "/bulan", "distance_km": 3.7, "job_type": "Part-time",
     "min_experience_label": "Min. Tidak wajib", "description": "Rawat taman perumahan: potong rumput, siram, dan bersihkan area hijau."},
    {"id": "jb_9", "business": "Pak Hasan", "title": "Tukang Renovasi Dapur", "category": "Tukang",
     "pay_amount": 180000, "pay_unit": "/hari", "distance_km": 5.0, "job_type": "Gig",
     "min_experience_label": "Min. 3 tahun", "description": "Renovasi dapur: pasang keramik, kabinet, dan instalasi air. Kerja rapi."},
    {"id": "jb_10", "business": "Catering Sedap", "title": "Bantu Masak Acara Weekend", "category": "Masak",
     "pay_amount": 200000, "pay_unit": "/acara", "distance_km": 2.8, "job_type": "Gig",
     "min_experience_label": "Min. 2 tahun", "description": "Bantu produksi catering saat acara akhir pekan. Cekatan dan higienis."},
    {"id": "jb_11", "business": "UMKM Batik Asri", "title": "Admin Media Sosial", "category": "Admin/Sosmed",
     "pay_amount": 1700000, "pay_unit": "/bulan", "distance_km": 2.3, "job_type": "Part-time",
     "min_experience_label": "Min. Tidak wajib", "description": "Kelola IG & TikTok toko batik: posting, balas DM, dan buat konten sederhana."},
    {"id": "jb_12", "business": "Studio Kreatif Nusa", "title": "Desainer Grafis Freelance", "category": "Desain",
     "pay_amount": 175000, "pay_unit": "/desain", "distance_km": 4.2, "job_type": "Gig",
     "min_experience_label": "Min. 1 tahun", "description": "Buat desain feed dan materi promosi klien. Kreatif dan revisi cepat."},
    {"id": "jb_13", "business": "Bimbel Cerdas", "title": "Tutor Matematika SMP", "category": "Tutor",
     "pay_amount": 85000, "pay_unit": "/jam", "distance_km": 2.0, "job_type": "Part-time",
     "min_experience_label": "Min. 2 tahun", "description": "Mengajar matematika SMP di bimbel sore hari. Sabar dan komunikatif."},
    {"id": "jb_14", "business": "Toko Online Maju", "title": "Admin Toko & Input Data", "category": "Admin/Sosmed",
     "pay_amount": 2000000, "pay_unit": "/bulan", "distance_km": 1.7, "job_type": "Full-time",
     "min_experience_label": "Min. Tidak wajib", "description": "Input pesanan, update stok, dan balas chat pembeli. Teliti dan rapi."},
    {"id": "jb_15", "business": "Agensi Konten Wangi", "title": "Content Writer Lepas", "category": "Menulis",
     "pay_amount": 80000, "pay_unit": "/artikel", "distance_km": 5.8, "job_type": "Gig",
     "min_experience_label": "Min. 1 tahun", "description": "Tulis artikel blog & SEO untuk klien. Bahasa enak dibaca, tepat waktu."},
    {"id": "jb_16", "business": "Event Organizer Meriah", "title": "Fotografer Acara", "category": "Fotografi/Video",
     "pay_amount": 450000, "pay_unit": "/event", "distance_km": 4.5, "job_type": "Gig",
     "min_experience_label": "Min. 2 tahun", "description": "Dokumentasi acara EO. Punya kamera sendiri, hasil tajam dan cepat."},
    {"id": "jb_17", "business": "CV Sukses Mandiri", "title": "Customer Service Harian", "category": "CS",
     "pay_amount": 2300000, "pay_unit": "/bulan", "distance_km": 3.0, "job_type": "Full-time",
     "min_experience_label": "Min. 1 tahun", "description": "Layani pelanggan via chat & telepon. Ramah, sabar, dan fast response."},
    {"id": "jb_18", "business": "Kanal Video Kreator", "title": "Video Editor Freelance", "category": "Fotografi/Video",
     "pay_amount": 220000, "pay_unit": "/video", "distance_km": 5.1, "job_type": "Gig",
     "min_experience_label": "Min. 1 tahun", "description": "Edit video YouTube & reels. Paham color grading dan motion sederhana."},
    {"id": "jb_19", "business": "Startup Lokal Rasa", "title": "Web Developer Pemula", "category": "Web Dev",
     "pay_amount": 1600000, "pay_unit": "/proyek", "distance_km": 3.6, "job_type": "Gig",
     "min_experience_label": "Min. Tidak wajib", "description": "Bangun landing page produk. Paham HTML/CSS/JS dasar, mau belajar."},
    {"id": "jb_20", "business": "Toko Kue Manis", "title": "Admin & CS Online", "category": "Admin/Sosmed",
     "pay_amount": 1800000, "pay_unit": "/bulan", "distance_km": 2.4, "job_type": "Part-time",
     "min_experience_label": "Min. Tidak wajib", "description": "Balas chat pembeli, catat pesanan kue, dan koordinasi pengiriman."},
]


REVIEW_POOL = [
    "Kerjanya rapi dan tepat waktu, recommended banget!",
    "Ramah, sopan, dan hasilnya memuaskan. Pasti panggil lagi.",
    "Cepat tanggap dan amanah. Terima kasih ya!",
    "Telaten dan detail, kerjaannya bersih sekali.",
    "Profesional dan komunikatif. Puas dengan hasilnya.",
    "Orangnya jujur dan bisa dipercaya, mantap!",
    "Hasil kerja bagus, sesuai ekspektasi. Recommended!",
    "Sabar dan hasilnya rapi, keluarga senang semua.",
    "Sat set sat set, kerjaan beres tanpa drama. Top!",
    "Pelayanan ramah dan cekatan, nggak nyesel pakai jasanya.",
    "Datang tepat waktu dan kerja sampai tuntas. Salut!",
    "Harganya worth it banget dengan kualitas kerjanya.",
]

REVIEW_AUTHORS = [
    "Budi S.", "Rina M.", "Pak Anton", "Bu Sari", "Dewi K.", "Hendra P.",
    "Ibu Wulan", "Mas Andi", "Kak Tia", "Pak Joko", "Mbak Lia", "Rudi H.",
]
